### PR TITLE
add master-22.06 

### PR DESCRIPTION
**Pull request by annaborn**
this contains debian packages for ubuntu 20 amd64

### CODE REVIEW

**Comment by annaborn** [comment]
Hello Thomas@2maz :)
Could you please merge it?

**Comment by 2maz** [comment]
Great to see that you managed to create a new release. I suggest you place your changes first into a testing branch, e.g., test,  with an updated ci pipeline for verification: https://github.com/rock-core/rock-osdeps-package_set/blob/master/.github/workflows/test.yml

**Comment by annaborn** [comment]
Hello Thomas @2maz !
Thank you for a tip! :)
I changed the goal branch to test and add new tests for ubuntu 20.04.

**Comment by annaborn** [comment]
@2maz Hello Thomas! The tests are ok. Should I consider smth else before I merge new debian release into master branch?
I have to say, that the new debian release contains only u20 amd64 due to the problem with qt4/qt5. But since our co-worker needs the debian packages, I would like to release it now. I am currently building new debian release for u20 and u18.

**Comment by 2maz** [comment]
> @2maz Hello Thomas! The tests are ok. Should I consider smth else before I merge new debian release into master branch?
> 
> I have to say, that the new debian release contains only u20 amd64 due to the problem with qt4/qt5. But since our co-worker needs the debian packages, I would like to release it now. I am currently building new debian release for u20 and u18.

What comes to mind is:
(a) update the Readme - in particular the table of supported arch/distro and 

(b) install the packages to rock.hb.dfki.de so that the latest documentation is also served from there.

**Pull request merged**
